### ISSUE TITLE
Log which games had no artwork and/or information found 

### ISSUE THREAD

**Issue by robertybob** [elpendor/ES-scraper#10]
So I can easily c&p them into google and edit the xml file myself. At the moment I'm having to go through the list of games manually on Emulationstaion with a notepad and pen, jotting down which ones have either their image or info missing. 

This would make my life a bit easier!

**Comment by elpendor** [comment]
Sounds simple enough. I'll try to add it.

**Comment by robertybob** [comment]
Has there been any progress made on this ?
