### ISSUE TITLE
(Customisable) "default" game image

### ISSUE THREAD

**Issue by robertybob** [elpendor/ES-scraper#13]
Just had a thought , with artwork for some games not being available this means that there's obviously a blank space which makes things look less visually appealing. 

I was wondering if there's a bit of code you could create which makes every rom show a default image (customisable per console perhaps) unless a user runs a scan and a correct image is found online.
For example, in my head I was thinking of an image of a sad Mario with the text 'artwork not available' for NES/GBA etc games.

Is this: a good (feasible) idea?

**Comment by elpendor** [comment]
I like the idea (I think at some point I thought about it too) but it's not really up to the scraper. Setting a custom image to each ROM with missing artwork is a bit of an overkill and not really a good practice.

I think ES should do that. Should be as simple as checking:

image tag empty? --> Show default/not available boxart

Maybe a description check could be added too.

I'll talk to Aloshi.

**Comment by robertybob** [comment]
Brilliant ! Thanks :)

**Comment by elpendor** [comment]
```
12:44 p.m. - Aloshi: it's a good idea
12:44 p.m. - Aloshi: i've written it on the sticky note of things to do
```

;)

**Comment by Aloshi** [comment]
Added to ES as a theme tag.
