### ISSUE TITLE
Doesn't use es_systems.cfg PATH as search location

### ISSUE THREAD

**Issue by transcendtient** [elpendor/ES-scraper#18]
I've placed my roms on a thumb drive and have been able to load games directly from Emulation Station (so my cfg is formatted correctly), but when I try to scrape roms I get no roms detected.

**Comment by transcendtient** [comment]
I finally found out you're referencing an es_system.cfg file in a different location than Emulation Station does.
Why is this?
This means you need the file in ~/.emulationstation and in /home/pi/.emulationstation.
Is this because I installed RetroPie as root?

**Comment by transcendtient** [comment]
Started scraping a library of 4000+ roms in 4 systems so here we go!

**Comment by elpendor** [comment]
I'm not sure I follow you. The scraper checks ~/.emulationstation/es_systems.cfg. 

> This means you need the file in ~/.emulationstation and in /home/pi/.emulationstation.

Assuming you're using the default "pi" user, ~/.emulationstation and /home/pi/.emulationstation are the same folder.

> but when I try to scrape roms I get no roms detected.

This tells me its not a config file problem at all. If that were the case there should be a warning about not having access to it.

Could you:
- Post your systems file
- run file ~/.emulationstation/es_systems.cfg and tell me the output

Also, why are you using the root user?

**Comment by transcendtient** [comment]
No, they're different locations for me. I'm positive of this as I had to copy my config file from my ~/.emulationstation folder to the /home/pi/.emulationstation folder.

The file in ~/.emulationstation was the file Emulation Station was using (ill post in a sec)

The file in /home/pi/.emulationstation was the default file, which was looking in the default locations 
which is /home/pi/RetroPie/roms (I overwrote this file with mine so I don't have it)

I'm new to linux and hate typing sudo in front of every command, so I roll as root.
The RetroPie install was done as root, updates are as root, I'm scraping as root right now.

The output is : ASCII text

NAME=Nintendo Entertainment System
PATH=/mnt/ROMusb/nes/
EXTENSION=.nes .NES
COMMAND=retroarch -c /home/pi/RetroPie/cfg/nes.cfg %ROM%
PLATFORMID=7

NAME=Super Nintendo Entertainment System
PATH=/mnt/ROMusb/snes/
EXTENSION=.smc .SMC
COMMAND=retroarch -c /home/pi/RetroPie/cfg/snes.cfg %ROM%
PLATFORMID=6

NAME=Multiple Arcade Machine Emulator
PATH=/mnt/ROMusb/mame2/
EXTENSION=.zip .ZIP
COMMAND=retroarch -c /home/pi/RetroPie/cfg/mame.cfg %ROM%
PLATFORMID=23

NAME=GameBoy Color
PATH=/mnt/ROMusb/gbc/
EXTENSION=.gbc .GBC
COMMAND=retroarch -c /home/pi/RetroPie/cfg/gbc.cfg %ROM%
PLATFORMID=41

#NAME=GameBoy Advance
#PATH=/mnt/ROMusb/nes/
#EXTENSION=.nes .NES
#COMMAND=retroarch -c /home/pi/RetroPie/cfg/nes.cfg %ROM%

#NAME=Megadrive/Mastersystem/Game Gear
#PATH=/mnt/ROMusb/nes/
#EXTENSION=.nes .NES
#COMMAND=retroarch -c /home/pi/RetroPie/cfg/nes.cfg %ROM%

#NAME=NeoGeo
#PATH=/mnt/ROMusb/nes/
#EXTENSION=.nes .NES
#COMMAND=retroarch -c /home/pi/RetroPie/cfg/nes.cfg %ROM%
