### ISSUE TITLE
Error while scraping Genesis/Megadrive games

### ISSUE THREAD

**Issue by chriskostelec** [elpendor/ES-scraper#19]
Hey there. I was able to scrape the folder before, but now when I try to scrape I get this error:

Scanning folder..(/home/pi/RetroPie/roms/megadrive)
Traceback (most recent call last):
  File "/home/pi/RetroPie/supplementary/ES-scraper/scraper.py", line 333, in <module>
    scanFiles(ES_systems[i])
  File "/home/pi/RetroPie/supplementary/ES-scraper/scraper.py", line 219, in scanFiles
    existinglist=ET.parse("gamelist.xml")
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1183, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 657, in parse
    self._root = parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1655, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1507, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: no element found: line 2, column 0

This is only if I create a blank gamelist.xml in the megadrive folder. If I don't, the scraper finds all the game art, but does not create and write into a gamelist.xml! There are no funky permissions set on the megadrive folder either. I'm at a loss!

**Comment by chriskostelec** [comment]
Well, for some reason it must of been because of my enormous library. Once I moved and scraped 400 files at a time it worked just fine. Possibly just an issue of too many files?

**Comment by elpendor** [comment]
The error is definitely related to the blank gamelist file but the scraper SHOULD save the xml just fine, no need to do that. 

I should check its contents first to avoid that from happening though. Gonna fix that later.

Could you send me the full list of filenames, so I can create some dummy files and do some testing?

**Comment by chriskostelec** [comment]
Here you go. 

http://dl.dropbox.com/u/52255546/filelist.txt

**Comment by elpendor** [comment]
> 712 games added.
> Done! List saved on /home/pi/roms/segatest/gamelist.xml
> All done!

Can't seem to find anything wrong here. 

Scraped all files, boxarts included and the gamelist was saved in the folder just fine.
