### ISSUE TITLE
Scraper syntax error

### ISSUE THREAD

**Issue by Starlight42** [elpendor/ES-scraper#25]
Hi! I am trying to run scraper.py but I encoutered an error:
$> python scraper.py 
  File "scraper.py", line 2
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

or :
./scraper.py 
./scraper.py: line 1: syntax error near unexpected token `newline'
./scraper.py: line 1:`<!DOCTYPE html>'

and my scraper.py :

pi@retropie ~ $ cat scraper.py 
# !/usr/bin/python

<!DOCTYPE html>
<html>
  <head prefix="og:...........

I don't really understand where is the problem since I have a fresh install of the RetroPie Project SD card Image (1.5) :/. Someone got an idea?

thanks!

**Comment by Aloshi** [comment]
Uhh, that's not a Python script.  It looks like your copy of scraper.py is corrupt somehow.  If your Pi is connected to the internet, try running `git pull`, which should update the script (assuming there isn't a bigger problem at play here).

**Comment by Starlight42** [comment]
Yeah! I have done some ***\* while downloading the script xD. Now I have got the good one!
Sorry for the inconvenience and thank you very much!
