### ISSUE TITLE
Subfolders in rom directory

### ISSUE THREAD

**Issue by petrockblog** [elpendor/ES-scraper#3]
For each system I have my ROMs organized in subfolders "a" ... "z". When I edit the es_systems.cfg and run the script as described in the README, I get this exemplary output:

TheGamesDB scraper for EmulationStation
Scanning folder..(/home/pi/RetroPie/roms/atari2600)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/doom)
Trying to identify DOOM1.WAD..
Trying to identify DOOM.WAD..
Game Found: Doom
Downloading boxart..
Trying to identify DOOM2.WAD..
Done! List saved on /home/pi/RetroPie/roms/doom/gamelist.xml
Scanning folder..(/home/pi/RetroPie/roms/gba)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/gbc)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/megadrive)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/nes)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/snes)
No new games added.
Scanning folder..(/home/pi/RetroPie/roms/mame)
Trying to identify supertnk.zip..
Trying to identify ripcord.zip..
No new games added.
All done!

Here, doom is the only system without subfolders. All other systems have subfolders. Do I have to use a special parameter when calling the script or does the script simply not look into these subfolders right now?

**Comment by elpendor** [comment]
Yep, the script does not look into subfolders, just the files (on the specified folder) whose extension match the one entered on the config file. 

I'll add it in a few minutes. :)

**Comment by elpendor** [comment]
Hmm, github won't let me commit. =/. Ok, seems to be working now.

A quick edit and.. done. Try it and let me know, hopefully I didn't break anything.

Edit: Small bug, I forgot something. I'll fix it later.

**Comment by elpendor** [comment]
Done. Let me know if you find something strange.
