### ISSUE TITLE
Wrong games matched

### ISSUE THREAD

**Issue by Olifiers** [elpendor/ES-scraper#34]
Hi there!

Some wrong matches across all platforms are happening with the latest version. Roughly 50% of the games are being matched to art with a similar name, but not quite.

Examples are:
Ogre Battles > Tactics Ogres
Mega Man X > Mega Man 9 (actually, all 'Mega Man' map to 'Mega Man 9'
Secret of Mana > Secret of Stars
etc...

There will always be a common word between the rom and the match. So 'Street Fighter 2 Turbo' will be matched with art for 'Street Cop'.

It's making the script unusable at the moment. Any game starting with 'Super' (Super R-Type, Super Turrican etc.) are is mapper to 'Super Mario All Stars' and so on.

Although my examples are SNES, this is taking place across all platforms at the moment, from MAME to Intellivision.

**Comment by Olifiers** [comment]
Hum... Seems like the GetGame.php at thegamesdb.net is ignoring the platform parameter and passing lots of matches as results.

Perhaps Scraper could filter the matches belonging to the same platform, this would make most matches work.

**Comment by elpendor** [comment]
It's a TheGamesDB bug. Someone has already reported it and provided a commit to fix it so its kinda pointless to change the way the scraper works because of it.

**Comment by elpendor** [comment]
Did a quick fix for it anyway. Try it and let me know.

**Comment by Olifiers** [comment]
Nice, will try it out, sir! ;)

And congrats for the great job.
